apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: team1-app  # 네임스페이스 지정
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 'image-registry.openshift-image-registry.svc:5000/team1-app/my-nginx-image:2024-11-13-09-51-13'
          ports:
            - containerPort: 80
