apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: team1-app  # 네임스페이스 지정
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: $OPENSHIFT_REGISTRY/team1-app/my-nginx-image:latest
          ports:
            - containerPort: 80
